### ISSUE TITLE
MAC用户怎么办？

### ISSUE THREAD

**Issue by yuanjunchai** [SilenceEagle/paper_downloader#38]
如题。我用mac系统，下载pywin32库的时候一直报错，尝试几番也没有解决问题。对应代码在：from win32com.client import Dispatch。可以帮帮我吗？

**Comment by SilenceEagle** [comment]
只有使用迅雷下载器时会调用pywin32，不过是windows系统的。我现在把迅雷相关的代码都去掉了（[b8d49e9](https://github.com/SilenceEagle/paper_downloader/commit/b8d49e91ab692c90d8634c1a2a6998e8fbed1427)），我也用mac系统跑了一下，可以跑通，你试试可以不？
**注意**需要把下载器改为**None**，提交的代码里都是调用IDM下载器，是windows的，不支持mac。
```python
downloader=None # use python's requests to download files
```

**Comment by yuanjunchai** [comment]
感谢您的及时回复～我在运行paper_downloader_NIPS.py时，采取url下载，但又报错了。这个报错我暂时没有找到源头，可以帮我看看吗？
<img width="1391" alt="image" src="https://github.com/SilenceEagle/paper_downloader/assets/25547974/99dc6056-427a-44b3-832a-1ec95db94ef1">

**Comment by SilenceEagle** [comment]
> 感谢您的及时回复～我在运行paper_downloader_NIPS.py时，采取url下载，但又报错了。这个报错我暂时没有找到源头，可以帮我看看吗？ <img alt="image" width="1391" src="https://private-user-images.githubusercontent.com/25547974/300371675-99dc6056-427a-44b3-832a-1ec95db94ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTg2MzIsIm5iZiI6MTcwNjUxODMzMiwicGF0aCI6Ii8yNTU0Nzk3NC8zMDAzNzE2NzUtOTlkYzYwNTYtNDI3YS00NGIzLTgzMmEtMWVjOTVkYjk0ZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMDMwZWRmMzVjZWQzZjczMTk4YTQ5NmM1ZDJhYzYxNTAwNGUzMGYzMmRlMDE2NDdjMjk1ZTk5NzI2NTZkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PoHC-kShaECf6EVMgh4p8e6VIY_myXyvsgcIMNkM9EA">

你把py文件末尾的
```python
downloader='IDM'
```
改为
```python
downloader=None
```
应该就可以了，这样会调用python的`requests`来下载论文，mac系统下不支持IDM。
